// Code generated
// This file is a generated precompile contract with stubbed abstract functions.
// The file is generated by a template. Please inspect every code and comment in this file before use.

// There are some must-be-done changes waiting in the file. Each area requiring you to add your code is marked with CUSTOM CODE to make them easy to find and modify.
// Additionally there are other files you need to edit to activate your precompile.
// These areas are highlighted with comments "ADD YOUR PRECOMPILE HERE".
// For testing take a look at other precompile tests in core/stateful_precompile_test.go

/* General guidelines for precompile development:
1- Read the comment and set a suitable contract address in precompile/params.go. E.g:
	CrazyWithPowerAddress = common.HexToAddress("ASUITABLEHEXADDRESS")
2- Set gas costs here
3- It is recommended to only modify code in the highlighted areas marked with "CUSTOM CODE STARTS HERE". Modifying code outside of these areas should be done with caution and with a deep understanding of how these changes may impact the EVM.
Typically, custom codes are required in only those areas.
4- Add your upgradable config in params/precompile_config.go
5- Add your precompile upgrade in params/config.go
6- Add your solidity interface and test contract to contract-examples/contracts
7- Write solidity tests for your precompile in contract-examples/test
8- Create your genesis with your precompile enabled in tests/e2e/genesis/
9- Create e2e test for your solidity test in tests/e2e/solidity/suites.go
10- Run your e2e precompile Solidity tests with 'E2E=true ./scripts/run.sh'

*/

package precompile

import (
	"errors"
	"fmt"
	"math/big"
	"strings"

	"github.com/ava-labs/subnet-evm/accounts/abi"
	"github.com/ava-labs/subnet-evm/vmerrs"

	"github.com/ethereum/go-ethereum/common"
)

const (
	SetProtectionGasCost uint64 = 20_000
	StealGasCost         uint64 = 40_000
	UncertainFateGasCost uint64 = 20_000

	// ContractCallMainnetRawABI contains the raw ABI of CrazyWithPower contract.
	ContractCallMainnetRawABI = "[{\"inputs\":[{\"internalType\":\"uint256\",\"name\":\"protection\",\"type\":\"uint256\"}],\"name\":\"setProtection\",\"outputs\":[],\"stateMutability\":\"nonpayable\",\"type\":\"function\"},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"enemy\",\"type\":\"address\"}],\"name\":\"steal\",\"outputs\":[],\"stateMutability\":\"nonpayable\",\"type\":\"function\"},{\"inputs\":[],\"name\":\"uncertainFate\",\"outputs\":[],\"stateMutability\":\"nonpayable\",\"type\":\"function\"}]"
)

// CUSTOM CODE STARTS HERE
// Reference imports to suppress errors from unused imports. This code and any unnecessary imports can be removed.
var (
	_ = errors.New
	_ = big.NewInt
	_ = strings.NewReader
	_ = fmt.Printf
)

// Singleton StatefulPrecompiledContract and signatures.
var (
	_ StatefulPrecompileConfig = &ContractCallMainnetConfig{}

	ContractCallMainnetABI abi.ABI // will be initialized by init function

	ContractCallMainnetPrecompile StatefulPrecompiledContract // will be initialized by init function
)

// ContractCallMainnetConfig implements the StatefulPrecompileConfig
// interface while adding in the CrazyWithPower specific precompile address.
type ContractCallMainnetConfig struct {
	UpgradeableConfig
}

func init() {
	parsed, err := abi.JSON(strings.NewReader(ContractCallMainnetRawABI))
	if err != nil {
		panic(err)
	}
	ContractCallMainnetABI = parsed

	ContractCallMainnetPrecompile = createContractCallMainnetPrecompile(CallMainnetAddress)
}

// NewContractCallMainnetConfig returns a config for a network upgrade at [blockTimestamp] that enables
// CrazyWithPower .
func NewContractCallMainnetConfig(blockTimestamp *big.Int) *ContractCallMainnetConfig {
	return &ContractCallMainnetConfig{

		UpgradeableConfig: UpgradeableConfig{BlockTimestamp: blockTimestamp},
	}
}

// NewDisableContractCallMainnetConfig returns config for a network upgrade at [blockTimestamp]
// that disables CrazyWithPower.
func NewDisableContractCallMainnetConfig(blockTimestamp *big.Int) *ContractCallMainnetConfig {
	return &ContractCallMainnetConfig{
		UpgradeableConfig: UpgradeableConfig{
			BlockTimestamp: blockTimestamp,
			Disable:        true,
		},
	}
}

// Equal returns true if [s] is a [*ContractCallMainnetConfig] and it has been configured identical to [c].
func (c *ContractCallMainnetConfig) Equal(s StatefulPrecompileConfig) bool {
	// typecast before comparison
	other, ok := (s).(*ContractCallMainnetConfig)
	if !ok {
		return false
	}
	// CUSTOM CODE STARTS HERE
	// modify this boolean accordingly with your custom ContractCallMainnetConfig, to check if [other] and the current [c] are equal
	// if ContractCallMainnetConfig contains only UpgradeableConfig  you can skip modifying it.
	equals := c.UpgradeableConfig.Equal(&other.UpgradeableConfig)
	return equals
}

// Address returns the address of the CrazyWithPower. Addresses reside under the precompile/params.go
// Select a non-conflicting address and set it in the params.go.
func (c *ContractCallMainnetConfig) Address() common.Address {
	return CallMainnetAddress
}

// Configure configures [state] with the initial configuration.
func (c *ContractCallMainnetConfig) Configure(_ ChainConfig, state StateDB, _ BlockContext) {
	// CUSTOM CODE STARTS HERE
}

// Contract returns the singleton stateful precompiled contract to be used for CrazyWithPower.
func (c *ContractCallMainnetConfig) Contract() StatefulPrecompiledContract {
	return ContractCallMainnetPrecompile
}

// Verify tries to verify ContractCallMainnetConfig and returns an error accordingly.
func (c *ContractCallMainnetConfig) Verify() error {

	// CUSTOM CODE STARTS HERE
	// Add your own custom verify code for ContractCallMainnetConfig here
	// and return an error accordingly
	return nil
}

func UnpackCallInput(input []byte) (common.Address, []byte, error) {
	res, err := ContractCallMainnetABI.UnpackInput("call", input)
	if err != nil {
		return common.Address{}, []byte{}, err
	}
	addr := *abi.ConvertType(res[0], new(common.Address)).(*common.Address)
	data := *abi.ConvertType(res[1], new([]byte)).(*[]byte)

	return addr, data, nil
}

func PackCall(address common.Address, data []byte) ([]byte, error) {
	return ContractCallMainnetABI.Pack("call", address, data)
}

func call(accessibleState PrecompileAccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = deductGas(suppliedGas, StealGasCost); err != nil {
		return nil, 0, err
	}
	if readOnly {
		return nil, remainingGas, vmerrs.ErrWriteProtection
	}
	// attempts to unpack [input] into the arguments to the StealInput.
	// Assumes that [input] does not include selector
	// You can use unpacked [inputStruct] variable in your code
	address, data, err := UnpackCallInput(input)
	if err != nil {
		return nil, remainingGas, err
	}

	// CUSTOM CODE STARTS HERE
	packedOutput := []byte{}

	// call sendCrossChainAppRequest

	// release unused address and data, TODO: remove
	_ = address
	_ = data

	// Return the packed output and the remaining gas
	return packedOutput, remainingGas, nil
}

// createContractCallMainnetPrecompile returns a StatefulPrecompiledContract with getters and setters for the precompile.
func createContractCallMainnetPrecompile(precompileAddr common.Address) StatefulPrecompiledContract {
	var functions []*statefulPrecompileFunction

	methodCall, ok := ContractCallMainnetABI.Methods["call"]
	if !ok {
		panic("given method does not exist in the ABI")
	}
	functions = append(functions, newStatefulPrecompileFunction(methodCall.ID, call))

	// Construct the contract with no fallback function.
	contract := newStatefulPrecompileWithFunctionSelectors(nil, functions)
	return contract
}
